### ISSUE TITLE
Type definitions cause compile errors in robot project that this is included with.

### ISSUE THREAD

**Issue by r4stered** [rzblue/navx-frc#10]
Gives compile errors on the robot project. int16_t is undefined.

**Comment by FarkasJoseph** [comment]
Strange, this doesn't occur for me, but it probably is compiler-specific

**Comment by rzblue** [comment]
Out of curiosity, what platform/compiler?

**Comment by r4stered** [comment]
> Out of curiosity, what platform/compiler?

This was compiling for desktop simulation in a 2023 beta 4 wpilib project. So Im pretty sure it used the Visual Studio compiler.

**Comment by rzblue** [comment]
That's odd. What version of Visual Studio do you have installed?

**Comment by r4stered** [comment]
> That's odd. What version of Visual Studio do you have installed?

Visual Studio 2022

**Comment by rzblue** [comment]
Huh. It obviously can't replicate in CI, but I'll merge the fix. Just FYI, I'm not sure if there will be another release for this repo since Studica has said they'll be releasing a beta soon. I'll probably do a release this weekend against wpilib beta-5 if they haven't.

**Comment by r4stered** [comment]
Sounds good to me! Thanks for the investigation

**Comment by rzblue** [comment]
closed in #11
