### ISSUE TITLE
C++ cannot be used in latest release

### ISSUE THREAD

**Issue by FarkasJoseph** [rzblue/navx-frc#8]
I tried using the maven repo as a vendor library in my team's code base, but found the c++ library to not be included. I also tried setting my version # to match that which is shown when looking at the maven publish action, but that didn't seem to work. I might be doing this wrong, so please correct me if I'm wrong, but I believe you need to make a new release that includes the latest commits.

**Comment by rzblue** [comment]
I just published version 2023.1.0-beta-3- the builds just got added to maven.

You'll need to update the vendor json to get the latest version.

**Comment by FarkasJoseph** [comment]
Thank you!
